nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Barry Digby, Nico Trummer
  description: Quantification, miRNA target prediction and differential expression
    analysis of circular RNAs
  force: false
  is_nfcore: true
  name: circrna
  org: nf-core
  outdir: .
  version: 0.0.1dev
