bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Barry Digby, Nico Trummer
  description: Quantification, miRNA target prediction and differential expression
    analysis of circular RNAs
  force: false
  is_nfcore: true
  name: circrna
  org: nf-core
  outdir: .
  skip_features: null
  version: 0.0.1dev
update: null
