contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #circrna channel"
    url: https://nfcore.slack.com/channels/circrna
    about: Discussion about the nf-core/circrna pipeline
