FROM community.wave.seqera.io/library/bioconductor-edger_bwa_hisat2_pysam_pruned:7bbe8b5420a7583d

# Install custom fork
RUN pip install git+https://github.com/nictru/CIRIquant.git@6b2def022765610ffe70b6b54621858189f61cb9
