FROM community.wave.seqera.io/library/bioconductor-edger_bwa_hisat2_pysam_pruned:f14fb8726c7f0cf8

# Install custom fork
RUN pip install git+https://github.com/nictru/CIRIquant.git@e4916ca7b3370cef54d76ca162be64792d8c1b16
