FROM community.wave.seqera.io/library/bioconductor-edger_bwa_hisat2_pysam_pruned:f14fb8726c7f0cf8

# Install custom fork
RUN pip install git+https://github.com/nictru/CIRIquant.git@ae6f27d3d14665fc632da4d0d1e47d774b8bdb31
